### PR TITLE
Payload Awareness and Question on Statuses

### PR DESCRIPTION
**Pull request by jakejohns**
How about some "Aware" interfaces and traits similar to [Psr\Log](https://github.com/php-fig/log/tree/master/Psr/Log)

This way I can write my Domain like so:

``` php

use Aura\Payload_Interface\PayloadAwareInterface;
use Aura\Payload_Interface\PayloadAwareTrait;

use Aura\Payload\Payload;

class Domain implements PayloadAwareInterface
{
    use PayloadAwareTrait;

    public function __invoke($input)
    {
        return $this->payload->setStatus(Payload::SUCCESS);
    }
}

```

And I can set my DI container like so:

``` php

use Aura\Di\Container;
use Aura\Di\ContainerConfig;

class Config extends ContainerConfig
{

    public function define(Container $di)
    {
        $di->setters['Aura\Payload_Interface\PayloadAwareInterface'] = [
            'setPayload' => $di->lazyNew('Aura\Payload\Payload')
        ];
    }
}

```
### On Statuses

On a side note (not included in this PR), what about moving the "Statuses" to
the interface similar to [Psr\Log\LogLevel](https://github.com/php-fig/log/blob/master/Psr/Log/LogLevel.php)

Then the domain above could become:

``` php

use Aura\Payload_Interface\PayloadAwareInterface;
use Aura\Payload_Interface\PayloadAwareTrait;
use Aura\Payload_Interface\Status;

class Domain implements PayloadAwareInterface
{
    use PayloadAwareTrait;

    public function __invoke($input)
    {
        return $this->payload->setStatus(Status::SUCCESS);
    }
}

```

Given a new "Status class" in the interface package:

``` php

namespace  Aura\Payload_Interface;

class Status
{
    const ACCEPTED = 'ACCEPTED';
    const AUTHENTICATED = 'AUTHENTICATED';
    const AUTHORIZED = 'AUTHORIZED';
    const CREATED = 'CREATED';
    const DELETED = 'DELETED';
    const ERROR = 'ERROR';
    const FAILURE = 'FAILURE';
    const FOUND = 'FOUND';
    const NOT_ACCEPTED = 'NOT_ACCEPTED';
    const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';
    const NOT_AUTHORIZED = 'NOT_AUTHORIZED';
    const NOT_CREATED = 'NOT_CREATED';
    const NOT_DELETED = 'NOT_DELETED';
    const NOT_FOUND = 'NOT_FOUND';
    const NOT_UPDATED = 'NOT_UPDATED';
    const NOT_VALID = 'NOT_VALID';
    const PROCESSING = 'PROCESSING';
    const SUCCESS = 'SUCCESS';
    const UPDATED = 'UPDATED';
    const VALID = 'VALID';
}

```

Thoughts?

### CODE REVIEW

**Comment by jakejohns** [comment]
@pmjones, I see you pulled #3 (cool), but no comment here?
Something smell here that I'm not considering?

**Comment by pmjones** [comment]
Hey @jakejohns -- the short version is, I'd rather not have implementation details in an Aura "Interface" package. The longer version is:

I've been going back-and-forth with myself as to whether a Trait counts as an implementation. After consideration, I think it does. One of the Aura library-level goals is "no dependencies", with a more recent relaxation of that restriction to allow for "interface only" dependencies. Basically, I don't want changes in a dependency to mess up the "main" library behaviors. A Trait would bust that, as would an Abstract. Even then, I might make allowances for third-party packages providing Traits and Abstracts (e.g. PSR-3), but those need to be few and far between; adding them in an Aura package proper is something I'd like to avoid.

Having said all that, it may be that the trait you're proposing here _might_ go in the Payload implementation package, but then it assumes that a `$payload` property is available, which I don't especially like (even though in this case it's unavoidable).

Hope all that makes sense.

**Comment by pmjones** [comment]
I've read the PR over again, and I just don't like the `*Aware`-style interfaces. They smack too much of setter injection, which I'd rather avoid by default. Hope you understand where I'm coming from here.

**Comment by pmjones** [comment]
Now, the PayloadFactory interface is reasonable; if you want to send that as a separate PR I can merge it toot-sweet.

**Comment by jakejohns** [comment]
(@pmjones, Please excuse the long comment on a closed PR, but I thought this
relevant to express here.)

Firstly, I agree.
Late last night I came to the conclusion that my impulse here was wrong.

My conception here was to provide mechanisms allowing the consuming code to
configure domain objects with a payload. On second thought, this seems quite
incorrect.

In general, the package providing the domain should be configuring what type of
payload the domain returns, not the consumer of that package. It does not make
sense for the consumer of the package to define a "universal payload" for all
components with a domain implementing aura/payload-interface.

Unlike the PSR\Log, which I referenced here, the payload is essentially
"specific" to the domain. It is not a universal utility to be configured and
passed around like Logger.

However, this raises some questions for me as to the "concrete" nature of
`Aura\Payload`. Should it not either _be_ `abstract` or at least "generally
thought of as abstract".

Would it not be more "_proper_" for a domain to _extend_ Payload, defining it's
own type, rather than simply use a generically typed implementation? It may be
onerous to _require_ such a paradigm by making the class `abstract`, but it
seems at least theoretically more "correct". I believe the concrete nature of
the class encouraged my wrong line of thinking.

Illustration:

```
$ tree
.
├── config
│   └── Config.php
├── src
│   ├── Domain
│   │   └── ComponentA
│   │       ├── ComponentAPayload.php
│   │       ├── ComponentAPayloadStatus.php
│   │       └── Service
│   │           ├── Bar.php
│   │           ├── Foo.php
│   │           └── Spec
│   │               ├── ReturnsComponentAPayloadInterface.php
│   │               └── ReturnsComponentAPayloadTrait.php
│   └── Web
│       └── Responder
│           └── ComponentAResponder.php
└── vendor
    └── aura
        └── payload
            └── src
                ├── AbstractPayload.php
                ├── PayloadInterface.php
                └── PayloadStatus.php
```

``` php

// Domain Specific Payload
namespace My\Domain\ComponentA;

use Aura\Payload\AbstractPayload;

class ComponentAPayload extends AbstractPayload
{
}

// Interface indicating the payload type returned
namespace My\Domain\ComponentA\Service\Spec;

use My\Domain\ComponentA\ComponentAPayload as Payload;

interface ReturnsComponentAPayloadInterface
{
    public function setPayload(Payload $payload);
}

// Trait to assist with configuration
namespace My\Domain\ComponentA\Service\Spec;

use My\Domain\ComponentA\ComponentAPayload as Payload;

trait ReturnsComponentAPayloadTrait
{
    protected $payload;

    public function setPayload(Payload $payload)
    {
        $this->payload = $payload;
    }
}

// Domain using Domain specific Payload and Status
namespace My\Domain\ComponentA\Service;

use My\Domain\ComponentA\PayloadStatus as Status;

class Foo implements Spec\ReturnsComponentAPayloadInterface
{
    use Spec\ReturnsComponentAPayloadTrait;

    public function __invoke()
    {
        $payload = clone $this->payload;
        return $payload->setStatus(Status::SUCCESS);
    }
}

// Domain specific status
namespace My\Domain\ComponentA;

use Aura\Payload\PayloadStatus;

class ComponentAPayloadStatus extends PayloadStatus
{
    const BAR = 'bar';            // Custom Status
    const SUCCESS = 'override';   // Override status
}

// Responder expecting Domain specific Payload 
namespace My\Web\Responder;

use My\Domain\ComponentA\ComponentAPayload;
use My\Domain\ComponentA\ComponentAPayloadStatus;

class ComponentAResponder
{

    public function __invoke(
        Request $request,
        Response $response,
        ComponentAPayload $payload
    ) {
        // ...
    }

}

// Component Configuration
use Aura\Di\Container;
use Aura\Di\ContainerConfig;

class Config extends ContainerConfig
{

    public function define(Container $di)
    {
        $di->setters[
            'My\Domain\ComponentA\Service\Spec\ReturnsComponentAPayloadInterface'
        ] = [
            'setPayload' => $di->lazyNew('My\Domain\ComponentA\ComponentAPayload')
        ];
    }
}
```

**Comment by pmjones** [comment]
I need to read that a couple times to digest it; when I do, I will reply. Thanks for the thoughtful response.

**Comment by jakejohns** [comment]
Certainly, take your time.

The short(er(ish)) version would be something like this:

My initial wrong impulse was that I wanted to do this, at an "application level
configuration":

``` php
use Aura\Di\Container;
use Aura\Di\ContainerConfig;

class ApplicationConfig extends ContainerConfig
{

    public function define(Container $di)
    {
        $di->setters['Aura\Payload_Interface\PayloadAwareInterface'] = [
            'setPayload' => $di->lazyNew('Aura\Payload\Payload')
        ];
    }
}
```

I believe that to be silly in retrospect.

However, I am thinking it makes sense to do this at the "package or component
configuration level":

``` php
use Aura\Di\Container;
use Aura\Di\ContainerConfig;

class MyComponentConfig extends ContainerConfig
{

    public function define(Container $di)
    {
        $di->setters['ReturnsMyPayloadInterface'] = [
            'setPayload' => $di->lazyNew('My\Payload')
        ];
    }
}
```

The implication here being that aura/payload should either be abstract, or at
least thought of as abstract-ish. And implementing code should strongly consider
extending the class with it's own type rather than using it generically. 

I still need to think about it more, but thought I'd share, especially since, in
my change in thinking, I've vacated the position which lead to this PR.

**Comment by pmjones** [comment]
Hi @jakejohns,

> the package providing the domain should be configuring what type of payload the domain returns, not the consumer of that package ... the payload is essentially "specific" to the domain. It is not a universal utility

All correct.

> Would it not be more "proper" for a domain to extend Payload, defining it's own type, rather than simply use a generically typed implementation?

Yes, it is definitely the more proper thing to do.

> It may be onerous to require such a paradigm by making the class abstract, but it seems at least theoretically more "correct".

This is where the main issue is for me as well. I'd like to balance "the right thing to do" (extend the Payload class for your own payload types) vs "get started quickly" (instantiate and return a generic Payload object, and/or expect a generic Payload object in your response-building logic).

One problem, for me at least, comes when you typehint against the generic Payload as a fallback. Reading this ...

``` php
    public function whatever(AbstractPayload $payload);
```

... rubs me the wrong way, though I am guilty of doing that from time to time. I'd much rather read one of these ...

``` php
    public function whatever(Payload $payload);

    public function another(PayloadInterface $payload);
```

Thus, providing a concrete class vs the abstract one feels nicer. Do you get where I'm coming from? Maybe there's some way to resolve that aesthetic irksomeness.

> I am thinking it makes sense to do this at the "package or component configuration level"

Yes, the package/component level is the place to build that out (although I do prefer constructor over setter injection).

> implementing code should strongly consider extending the class with it's own type rather than using it generically.

Again, I agree, though again, my concern is about stepping people into it gently, since it's not that common in PHP land (that I know of anyway).

**Pull request closed without merging**
