### PR TITLE
Change PHPUnit req to play nice w/ travis

### PR DESCRIPTION
**Pull request by jakejohns**
Lets see if this makes it actually pass tests...

### CODE REVIEW

**Comment by jakejohns** [comment]
Well, it makes the little dots green, but I guess there's still some kinnda issue cuz  hhvm still says:
>$ ./vendor/bin/phpunit --coverage-clover=coverage.clover
> PHPUnit 5.7.21 by Sebastian Bergmann and contributors.
> Error:         No code coverage driver is available

I assume it's related to this:
sebastianbergmann/php-code-coverage#365

**Comment by pmjones** [comment]
Nice. @jakejohns Do you have a Twitter account you'd like to reveal? Want to make sure you get feedback/notification/etc when I refer to your work.

**Comment by jakejohns** [comment]
fwiw,  I guess [this won't be required after Friday, September 1 2017 ](https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming)

I actually don't tweet. I know it's weird. Github here is the closet thing to "social media" I ever post on.

**Comment by pmjones** [comment]
Dude, if you're not already there, stay away. You are saner for it. Forget I said anything. Thanks for everything you do. :-)

**Pull request merged**
